### ISSUE TITLE
帮忙看下AttributeError: 'TarFile' object has no attribute '__exit__'是怎么回事

### ISSUE THREAD

**Issue by crazybinx** [pkeropen/flink-parcel#4]
Found parcel FLINK-1.9.1-BIN-SCALA_2.12-el6.parcel
Traceback (most recent call last):
  File "cm_ext/make_manifest/make_manifest.py", line 115, in <module>
    manifest = make_manifest(path)
  File "cm_ext/make_manifest/make_manifest.py", line 79, in make_manifest
    with tarfile.open(fullpath, 'r') as tar:
AttributeError: 'TarFile' object has no attribute '__exit__'

**Comment by crazybinx** [comment]
已解决，是python版本的问题python2.6.6升级到2.7.15后就没有问题了
